<hr>
ComcaveTeamwork/CTP_01_TableReader pull request #29
Opened 2021-08-24 09:29 UTC by Hostmisha1

Horizontal Linie

2021-08-24 10:03 UTC, HolgerSin requested changes
Da hatte ich die Aufgabe falsch formuliert, ich hätte die horizontale Linie bitte  noch unter dem Button, also ganz unten.

2021-08-24 11:57 UTC, danjan09 approved these changes
Olaf approves

2021-08-24 12:20 UTC, Hostmisha1 commented
> 
> 
> Da hatte ich die Aufgabe falsch formuliert, ich hätte die horizontale Linie bitte noch unter dem Button, also ganz unten.

Habe es angepasst, Daniel auch 👯‍♀️ :)

2021-08-25 12:56 UTC, HolgerSin commented
Beide Themen erledigt

2021-08-25 12:56 UTC, closed without merging