fatihkoeksal feature 2 namen hinzufügen ++Draft PR++
ComcaveTeamwork/CTP_01_TableReader pull request #52
Opened 2021-08-28 12:58 UTC by fatihkoeksal

Namen zum Array in tableReader.js hinzugefügt.

2021-08-28 17:27 UTC, mauricekoenig submitted a review, later dismissed
Passt!

2021-08-28 18:05 UTC, HolgerSin approved these changes
checked ok

2021-08-30 08:39 UTC, RabuMia approved these changes

2021-08-30 09:02 UTC, Hostmisha1 approved these changes
passt

2021-08-30 12:59 UTC, Indu1284 reviewed
This variante also looks good...we have one more variante of the same array

2021-08-30 13:02 UTC, HolgerSin commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2021-08-30 22:43 UTC, fatihkoeksal commented
conflict corrected ✔️

2021-08-31 09:10 UTC, HolgerSin requested changes
Ich denke da hast du versehentlich die readDataFromFile Funktion von Maurice gelöscht.  Bitte erstmal so lassen, später besprechen. Gutes Übungsbeispiel!

2021-08-31 13:42 UTC, danjan09 approved these changes

2021-09-01 06:55 UTC, HolgerSin approved these changes

2021-09-01 15:09 UTC, mauricekoenig commented
@HolgerSin was war jetzt gleich mit dem Request hier? Kann approved werden, weil die Funktion wieder enthalten ist, right?

2021-09-01 15:09 UTC, mauricekoenig approved these changes

2021-09-01 15:19 UTC, HolgerSin commented
> @HolgerSin was war jetzt gleich mit dem Request hier? Kann approved werden, weil die Funktion wieder enthalten ist, right?

Korrekt

2021-09-03 06:50 UTC, nicopape reviewed
passt

2021-09-03 09:01 UTC, Indu1284 approved these changes
Looks Good

2021-09-03 09:01 UTC, merged