Create CC_Standort_Bielefeld.md
ComcaveTeamwork/CTP_01_TableReader pull request #59
Opened 2021-08-30 06:44 UTC by Hostmisha1

erstellen einer Liste mit dem Standort Bielefeld im Markdown Format (dicke überschrift)

2021-08-30 08:43 UTC, RabuMia approved these changes

2021-08-30 08:57 UTC, fatihkoeksal approved these changes
✔️

2021-08-30 08:58 UTC, mauricekoenig approved these changes
Bin zwar etwas verwirrt, was den Auftrag angeht, aber scheint zu passen :D

2021-08-30 09:05 UTC, Hostmisha1 commented
war auch sehr verwirrt darüber, aber holger sagt misha macht, so easy~

2021-08-30 09:57 UTC, HolgerSin requested changes
Bitte die Datei noch umbenennen, nicht nur den PR Titel :-)
Am besten bitte "Liste_Standorte.md"
Wir werden die Datei noch nicht kurzfristig brauchen, ist eher im Vorgriff auf Datenbanken...

2021-08-30 13:11 UTC, Hostmisha1 commented
habs umbenannt in Liste_Standorte.md

2021-08-30 22:57 UTC, fatihkoeksal approved these changes
✔️

2021-08-31 09:17 UTC, HolgerSin approved these changes

2021-08-31 09:24 UTC, danjan09 approved these changes

2021-09-01 15:08 UTC, mauricekoenig approved these changes

2021-09-02 05:50 UTC, merged